---
title: "Class 17"
author: "Joshua Mac"
format: pdf
date: Mar 10, 2025
---

```{r}
# BiocManager::install("tximport") in console
library(tximport)

folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```

```{r}
head(txi.kallisto$counts)
```

How many transcripts we have for each sample:
```{r}
colSums(txi.kallisto$counts)
```

How many transcripts detected in at least one sample:
```{r}
sum(rowSums(txi.kallisto$counts)>0)
```

Filtering out no reads:
```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
```

Filtering out no change over samples:
```{r}
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```

*PCA*

Now we return to PCA as an exploratory analysis technique.

```{r}
pca <- prcomp(t(x), scale=TRUE)
```

```{r}
summary(pca)
```
```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```

**Q1. Use ggplot to make a similar figure of PC1 vs PC2 and a separate figure PC1 vs PC3 and PC2 vs. PC3.**

> A1. See code below.

```{r}
library(ggplot2)
library(ggrepel)

# Make metadata object for the samples (had to use hint for this)
colData <- data.frame(condition = factor(rep(c("control", "treatment"), each = 2)))
rownames(colData) <- colnames(txi.kallisto$counts)

# Make the data.frame for ggplot 
df <- as.data.frame(pca$x)
df$Condition <- as.factor(colData$condition)

ggplot(df) +
  aes(PC1, PC2, col=Condition) +
  geom_point() +
  geom_text_repel(label=rownames(df)) +
  theme_bw()
```

```{r}
ggplot(df) +
  aes(PC1, PC3, col=Condition) +
  geom_point() +
  geom_text_repel(label=rownames(df)) +
  theme_bw()
```

```{r}
ggplot(df) +
  aes(PC2, PC3, col=Condition) +
  geom_point() +
  geom_text_repel(label=rownames(df)) +
  theme_bw()
```

